name: Terraform Destroy
run-name: ${{ github.actor }} is running Terraform Destroy on ${{ github.repository }} repository.

on:
    workflow_dispatch

jobs:
    tf-destroy:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'

        steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Terraform Destroy Workflow
           working-directory: prd
           run: |
             terraform init
             terraform plan -destroy
             terraform destroy -auto-approve